
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy4-frontend
  namespace: NamespaceName
spec:
  replicas: 3
  selector:
    matchLabels:
      tag: label4-frontend
  template:
    metadata:
      labels:
        tag: label4-frontend
    spec:
      containers:
      - name: ctr4-frontend
        image: gcr.io/google-samples/gb-frontend:v4
        ports:
        - containerPort: 80
        env:
        - name: GET_HOSTS_FROM
          value: dns
...
