
---
apiVersion: v1
kind: Service
metadata:
  name: svc29-jenkins-ha
spec:
  selector:
    tag: label29
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080  # default port on container where Jenkins dashboard is launched
status:
  loadBalancer:
    ingress:
    - ip: 35.184.79.192
...
